on: [push, pull_request]
name: osx-ci
jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        ghc: ['9.2']
        cabal: ['3.6']
    name: Haskell GHC ${{ matrix.ghc }}
    steps:
      - name: CPU info
        run: |
            sysctl -n machdep.cpu.features
            sysctl -n machdep.cpu.leaf7_features

      - name: remove xcode devtools
        run: sudo rm -rf /Library/Developer/CommandLineTools/SDKs

      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        id: setup-haskell-cabal # <--- give it a name for later cache usage
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - run: |
          cabal update
          cabal freeze

      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - run: |
          cabal configure --enable-tests --enable-benchmarks
          cabal build

      - run: |
          cabal test --test-show-details=direct

      - run: |
          cabal haddock
          cabal check
          cabal sdist
