name: osx-ci
on: [push, pull_request]

jobs:
  build:
    name: Build on macos-10.15:ghc-${{ matrix.ghc }}:cabal-${{ matrix.cabal }}
    runs-on: macos-10.15
    strategy:
      matrix:
        ghc: ['8.6.5', '8.8.4', '8.10.2']
        cabal: ['2.4.1.0', '3.4.0.0']
        exclude:
          # GHC 8.8+ only works with cabal v3+
          - ghc: 8.8.4
            cabal: 2.4.1.0
          - ghc: 8.10.2
            cabal: 2.4.1.0
    env:
        CONFIG: "--enable-tests --enable-benchmarks"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Haskell
        uses: actions/setup-haskell@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - run: cabal v2-update
      - run: cabal v2-freeze $CONFIG

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - run: "cabal update && cabal v2-build $CONFIG"

      - if: "matrix.cabal < '3'"
        run: cabal v2-test
      - if: "matrix.cabal >= '3'"
        run: cabal v2-test --test-show-details=direct

      - run: cabal check
      - run: cabal v2-haddock
      - run: cabal v2-sdist
